# This file was auto-generated by /home/iswhy/src/nwchem-6.8/DEV_intel-18.0.0_impi-2018.0.128/contrib/distro-tools/build_nwchem
export NWCHEM_TOP=/home/iswhy/src/nwchem-6.8/DEV_intel-18.0.0_impi-2018.0.128
export NWCHEM_TARGET=LINUX64
export NWCHEM_MODULES="smallqm nwxc"
export NWCHEM_MPIF_WRAP="/usr/local/packages/mvapich2/2.3.3/nc23zj7q/bin/mpif90"
export NWCHEM_MPIC_WRAP="/usr/local/packages/mvapich2/2.3.3/nc23zj7q/bin/mpicc"
export NWCHEM_MPICXX_WRAP="/usr/local/packages/mvapich2/2.3.3/nc23zj7q/bin/mpicxx"
export NWCHEM_LONG_PATHS=Y
export USE_NOFSCHECK=Y
export USE_MPI=y
export USE_MPIF=y
export USE_MPIF4=y
export MPI_INCLUDE=""
export MPI_LIB=""
export LIBMPI=""
export FC=mpif90
export CC=mpicc
export CXX=mpicxx
export ARMCI_NETWORK=OPENIB
export MSG_COMMS=MPI
export IB_INCLUDE="/usr/include"
export IB_LIB="/usr/lib64"
export IB_LIB_NAME="-libverbs"
export SLURMOPT=-lslurm
export SLURM=y
export BLASOPT="-mkl"
export PYTHON_EXE=/usr/bin/python
export PYTHONVERSION=2.7
export USE_PYTHON64=yes
export PYTHONPATH=./:/home/iswhy/src/nwchem-6.8/DEV_intel-18.0.0_impi-2018.0.128/contrib/python/
export PYTHONHOME=/usr
export PYTHONLIBTYPE=so
function renwc()
{
   make FC=$FC ; pushd $NWCHEM_TOP/src ; make FC=$FC link ; popd
}
